export const REQUEST_TODO_TOGGLE  = 'REQUEST_TODO_TOGGLE';
export const TODO_TOGGLE_SUCCESS  = 'TODO_TOGGLE_SUCCESS';
export const TODO_TOGGLE_FAIL     = 'TODO_TOGGLE_FAIL';

export const TEXT_INPUT_CHANGE = 'TEXT_INPUT_CHANGE';
export const REQUEST_ADD_TODO = 'REQUEST_ADD_TODO';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAIL = 'ADD_TODO_FAIL';